service: minion-buyer-api

package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: sa-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  getProducts:
    handler: src/functions/getProducts.getProducts
    events:
      - http:
          path: /products
          method: get
          cors: true