service: minion-buyer-api

package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: sa-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  registerUser:
    handler: src/functions/registerUser.registerUser
      events:
        - http:
            path: /users
            method: post
            cors: true
            request:
              schema:
                application/json: ${file(src/schema/register_user.json)}
  getProducts:
    handler: src/functions/getProducts.getProducts
    events:
      - http:
          path: /products
          method: get
          cors: true
  buyProducts:
    handler: src/functions/buyProducts.buyProducts
    events:
      - http:
          path: /user/products
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(src/schema/post_products.json)}